worker_processes  1;

events {
    worker_connections  1024;
}

rtmp {
    server {
        listen 1935;  # RTMP server port

        application multi_live {
            live on;

            # Forward stream to Twitch
            push rtmp://live.twitch.tv/app/live_28201488_UzS6ZRK1Jgn6Iinkn2LvsDMtMEqZqj;

            # Forward stream to YouTube
            push rtmp://a.rtmp.youtube.com/live2/075k-m2vw-09gm-5ywy-42aq;

            # Forward stream to Facebook
            # push rtmp://live-api-s.facebook.com:80/rtmp/FACEBOOK_STREAM_KEY;

            # Forward stream to TikTok  
            # push rtmp://live-api-s.tiktok.com:80/rtmp/TIKTOK_STREAM_KEY;
        }
    }
}
